#  Copyright (c) 2025 by ESA DTE-S2GOS team and contributors
#  Permissions are hereby granted under the terms of the Apache 2.0 License:
#  https://opensource.org/license/apache-2-0.

site_name: ESA DTE-S2GOS Client
repo_url: https://github.com/s2gos-dev/s2gos-client
repo_name: s2gos-dev/s2gos-client

copyright: Copyright &copy; 2025 ESA DTE-S2GOS Team

nav:
  - Overview: index.md
  - About: about.md

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.ico
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: blue grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: blue grey
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/s2gos-dev/s2gos-client
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/s2gos/

plugins:
  - search
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_root_toc_entry: true
            show_root_heading: true
            show_source: true
            heading_level: 2
            annotations_path: brief
            members_order: source
