# generated by datamodel-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-22T13:18:35+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any, Optional, Union

from pydantic import (
    AnyUrl,
    BaseModel,
    ConfigDict,
    Field,
    PositiveFloat,
    RootModel,
    conint,
)


class ApiError(BaseModel):
    """
    API error based on RFC 7807
    """

    model_config = ConfigDict(
        extra="allow",
    )
    type: str
    title: Optional[str] = None
    status: Optional[int] = None
    detail: Optional[str] = None
    instance: Optional[str] = None


class ConfClasses(BaseModel):
    conformsTo: list[str]


class Response(Enum):
    raw = "raw"
    document = "document"


class Type(Enum):
    process = "process"


class Link(BaseModel):
    href: str
    rel: Optional[str] = Field(None, examples=["service"])
    type: Optional[str] = Field(None, examples=["application/json"])
    hreflang: Optional[str] = Field(None, examples=["en"])
    title: Optional[str] = None


class MaxOccurs(Enum):
    unbounded = "unbounded"


class Subscriber(BaseModel):
    """
    Optional URIs for callbacks for this job.

    Support for this parameter is not required and the parameter may be
    removed from the API definition, if conformance class **'callback'**
    is not listed in the conformance declaration under `/conformance`.
    """

    successUri: Optional[AnyUrl] = None
    inProgressUri: Optional[AnyUrl] = None
    failedUri: Optional[AnyUrl] = None


class StatusCode(Enum):
    accepted = "accepted"
    running = "running"
    successful = "successful"
    failed = "failed"
    dismissed = "dismissed"


class JobControlOptions(Enum):
    sync_execute = "sync-execute"
    async_execute = "async-execute"
    dismiss = "dismiss"


class TransmissionMode(Enum):
    value = "value"
    reference = "reference"


class Type1(Enum):
    array = "array"
    boolean = "boolean"
    integer = "integer"
    number = "number"
    object = "object"
    string = "string"


class Format(BaseModel):
    mediaType: Optional[str] = None
    encoding: Optional[str] = None
    schema_: Optional[Union[str, dict[str, Any]]] = Field(None, alias="schema")


class Metadata(BaseModel):
    title: Optional[str] = None
    role: Optional[str] = None
    href: Optional[str] = None


class AdditionalParameter(BaseModel):
    name: str
    value: list[Union[str, float, int, list[dict[str, Any]], dict[str, Any]]]


class Reference(BaseModel):
    field_ref: str = Field(..., alias="$ref")


class Crs(Enum):
    http___www_opengis_net_def_crs_OGC_1_3_CRS84 = (
        "http://www.opengis.net/def/crs/OGC/1.3/CRS84"
    )
    http___www_opengis_net_def_crs_OGC_0_CRS84h = (
        "http://www.opengis.net/def/crs/OGC/0/CRS84h"
    )


class Bbox(BaseModel):
    bbox: list[float]
    crs: Optional[Crs] = Crs.http___www_opengis_net_def_crs_OGC_1_3_CRS84


class LandingPage(BaseModel):
    title: Optional[str] = Field(None, examples=["Example processing server"])
    description: Optional[str] = Field(
        None,
        examples=["Example server implementing the OGC API - Processes 1.0 Standard"],
    )
    links: list[Link]


class JobInfo(BaseModel):
    processID: Optional[str] = None
    type: Type
    jobID: str
    status: StatusCode
    message: Optional[str] = None
    created: Optional[datetime] = None
    started: Optional[datetime] = None
    finished: Optional[datetime] = None
    updated: Optional[datetime] = None
    progress: Optional[conint(ge=0, le=100)] = None
    links: Optional[list[Link]] = None
    traceback: Optional[list[str]] = None


class Output(BaseModel):
    format: Optional[Format] = None
    transmissionMode: Optional[TransmissionMode] = TransmissionMode.value


class AdditionalParameters(Metadata):
    parameters: Optional[list[AdditionalParameter]] = None


class DescriptionType(BaseModel):
    title: Optional[str] = None
    description: Optional[str] = None
    keywords: Optional[list[str]] = None
    metadata: Optional[list[Metadata]] = None
    additionalParameters: Optional[AdditionalParameters] = None


class Schema(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: Optional[str] = None
    multipleOf: Optional[PositiveFloat] = None
    maximum: Optional[float] = None
    exclusiveMaximum: Optional[bool] = False
    minimum: Optional[float] = None
    exclusiveMinimum: Optional[bool] = False
    maxLength: Optional[conint(ge=0)] = None
    minLength: Optional[conint(ge=0)] = 0
    pattern: Optional[str] = None
    maxItems: Optional[conint(ge=0)] = None
    minItems: Optional[conint(ge=0)] = 0
    uniqueItems: Optional[bool] = False
    maxProperties: Optional[conint(ge=0)] = None
    minProperties: Optional[conint(ge=0)] = 0
    required: Optional[list[str]] = Field(None, min_length=1)
    enum: Optional[list[dict[str, Any]]] = Field(None, min_length=1)
    type: Optional[Type1] = None
    not_: Optional[Union[Schema, Reference]] = Field(None, alias="not")
    allOf: Optional[list[Union[Schema, Reference]]] = None
    oneOf: Optional[list[Union[Schema, Reference]]] = None
    anyOf: Optional[list[Union[Schema, Reference]]] = None
    items: Optional[Union[list[Union[Schema, Reference]], Schema, Reference]] = None
    properties: Optional[dict[str, Union[Schema, Reference]]] = None
    additionalProperties: Optional[Union[Schema, Reference, bool]] = True
    description: Optional[str] = None
    format: Optional[str] = None
    default: Optional[Union[bool, float, int, str, list, dict[str, Any]]] = None
    nullable: Optional[bool] = False
    readOnly: Optional[bool] = False
    writeOnly: Optional[bool] = False
    example: Optional[dict[str, Any]] = None
    deprecated: Optional[bool] = False
    contentMediaType: Optional[str] = None
    contentEncoding: Optional[str] = None
    contentSchema: Optional[str] = None


class QualifiedInputValue(Format):
    value: Union[str, float, int, bool, list[str], dict[str, Any], Bbox]


class JobList(BaseModel):
    jobs: list[JobInfo]
    links: list[Link]


class ProcessSummary(DescriptionType):
    id: str
    version: str
    jobControlOptions: Optional[list[JobControlOptions]] = None
    outputTransmission: Optional[list[TransmissionMode]] = None
    links: Optional[list[Link]] = None


class InputDescription(DescriptionType):
    minOccurs: Optional[int] = 1
    maxOccurs: Optional[Union[int, MaxOccurs]] = None
    schema_: Union[Schema, Reference] = Field(..., alias="schema")


class OutputDescription(DescriptionType):
    schema_: Union[Schema, Reference] = Field(..., alias="schema")


class InlineOrRefData(
    RootModel[Union[str, float, int, bool, list, Bbox, QualifiedInputValue, Link]]
):
    root: Union[str, float, int, bool, list, Bbox, QualifiedInputValue, Link]


class ProcessList(BaseModel):
    processes: list[ProcessSummary]
    links: list[Link]


class Process(ProcessSummary):
    inputs: Optional[dict[str, InputDescription]] = None
    outputs: Optional[dict[str, OutputDescription]] = None


class Execute(BaseModel):
    inputs: Optional[dict[str, Union[InlineOrRefData, list[InlineOrRefData]]]] = None
    outputs: Optional[dict[str, Output]] = None
    response: Optional[Response] = Response.raw
    subscriber: Optional[Subscriber] = None


class Results(RootModel[Optional[dict[str, InlineOrRefData]]]):
    root: Optional[dict[str, InlineOrRefData]] = None


class InlineResponse200(
    RootModel[
        Union[
            str, float, int, dict[str, Any], list[dict[str, Any]], bool, bytes, Results
        ]
    ]
):
    root: Union[
        str, float, int, dict[str, Any], list[dict[str, Any]], bool, bytes, Results
    ]


Schema.model_rebuild()
