# generated by datamodel-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-10T12:02:13+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional, Union

from pydantic import (
    AnyUrl,
    BaseModel,
    ConfigDict,
    Field,
    PositiveFloat,
    RootModel,
    conint,
)


class Exception(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    type: str
    title: Optional[str] = None
    status: Optional[int] = None
    detail: Optional[str] = None
    instance: Optional[str] = None


class ConfClasses(BaseModel):
    conformsTo: List[str]


class Response(Enum):
    raw = "raw"
    document = "document"


class Type(Enum):
    process = "process"


class Link(BaseModel):
    href: str
    rel: Optional[str] = Field(None, examples=["service"])
    type: Optional[str] = Field(None, examples=["application/json"])
    hreflang: Optional[str] = Field(None, examples=["en"])
    title: Optional[str] = None


class MaxOccurs(Enum):
    unbounded = "unbounded"


class Subscriber(BaseModel):
    successUri: Optional[AnyUrl] = None
    inProgressUri: Optional[AnyUrl] = None
    failedUri: Optional[AnyUrl] = None


class StatusCode(Enum):
    accepted = "accepted"
    running = "running"
    successful = "successful"
    failed = "failed"
    dismissed = "dismissed"


class JobControlOptions(Enum):
    sync_execute = "sync-execute"
    async_execute = "async-execute"
    dismiss = "dismiss"


class TransmissionMode(Enum):
    value = "value"
    reference = "reference"


class Type1(Enum):
    array = "array"
    boolean = "boolean"
    integer = "integer"
    number = "number"
    object = "object"
    string = "string"


class Format(BaseModel):
    mediaType: Optional[str] = None
    encoding: Optional[str] = None
    schema_: Optional[Union[str, Dict[str, Any]]] = Field(None, alias="schema")


class Metadata(BaseModel):
    title: Optional[str] = None
    role: Optional[str] = None
    href: Optional[str] = None


class AdditionalParameter(BaseModel):
    name: str
    value: List[Union[str, float, int, List[Dict[str, Any]], Dict[str, Any]]]


class Reference(BaseModel):
    field_ref: str = Field(..., alias="$ref")


class Crs(Enum):
    http___www_opengis_net_def_crs_OGC_1_3_CRS84 = (
        "http://www.opengis.net/def/crs/OGC/1.3/CRS84"
    )
    http___www_opengis_net_def_crs_OGC_0_CRS84h = (
        "http://www.opengis.net/def/crs/OGC/0/CRS84h"
    )


class Bbox(BaseModel):
    bbox: List[float]
    crs: Optional[Crs] = "http://www.opengis.net/def/crs/OGC/1.3/CRS84"


class LandingPage(BaseModel):
    title: Optional[str] = Field(None, examples=["Example processing server"])
    description: Optional[str] = Field(
        None,
        examples=["Example server implementing the OGC API - Processes 1.0 Standard"],
    )
    links: List[Link]


class StatusInfo(BaseModel):
    processID: Optional[str] = None
    type: Type
    jobID: str
    status: StatusCode
    message: Optional[str] = None
    created: Optional[datetime] = None
    started: Optional[datetime] = None
    finished: Optional[datetime] = None
    updated: Optional[datetime] = None
    progress: Optional[conint(ge=0, le=100)] = None
    links: Optional[List[Link]] = None


class Output(BaseModel):
    format: Optional[Format] = None
    transmissionMode: Optional[TransmissionMode] = "value"


class AdditionalParameters(Metadata):
    parameters: Optional[List[AdditionalParameter]] = None


class DescriptionType(BaseModel):
    title: Optional[str] = None
    description: Optional[str] = None
    keywords: Optional[List[str]] = None
    metadata: Optional[List[Metadata]] = None
    additionalParameters: Optional[AdditionalParameters] = None


class Schema(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: Optional[str] = None
    multipleOf: Optional[PositiveFloat] = None
    maximum: Optional[float] = None
    exclusiveMaximum: Optional[bool] = False
    minimum: Optional[float] = None
    exclusiveMinimum: Optional[bool] = False
    maxLength: Optional[conint(ge=0)] = None
    minLength: Optional[conint(ge=0)] = 0
    pattern: Optional[str] = None
    maxItems: Optional[conint(ge=0)] = None
    minItems: Optional[conint(ge=0)] = 0
    uniqueItems: Optional[bool] = False
    maxProperties: Optional[conint(ge=0)] = None
    minProperties: Optional[conint(ge=0)] = 0
    required: Optional[List[str]] = Field(None, min_length=1)
    enum: Optional[List[Dict[str, Any]]] = Field(None, min_length=1)
    type: Optional[Type1] = None
    not_: Optional[Union[Schema, Reference]] = Field(None, alias="not")
    allOf: Optional[List[Union[Schema, Reference]]] = None
    oneOf: Optional[List[Union[Schema, Reference]]] = None
    anyOf: Optional[List[Union[Schema, Reference]]] = None
    items: Optional[Union[list[Union[Schema, Reference]], Schema, Reference]] = None
    properties: Optional[Dict[str, Union[Schema, Reference]]] = None
    additionalProperties: Optional[Union[Schema, Reference, bool]] = True
    description: Optional[str] = None
    format: Optional[str] = None
    default: Optional[Union[bool, float, int, str, List, Dict[str, Any]]] = None
    nullable: Optional[bool] = False
    readOnly: Optional[bool] = False
    writeOnly: Optional[bool] = False
    example: Optional[Dict[str, Any]] = None
    deprecated: Optional[bool] = False
    contentMediaType: Optional[str] = None
    contentEncoding: Optional[str] = None
    contentSchema: Optional[str] = None


class QualifiedInputValue(Format):
    value: Union[str, float, int, bool, List[str], Dict[str, Any], Bbox]


class JobList(BaseModel):
    jobs: List[StatusInfo]
    links: List[Link]


class ProcessSummary(DescriptionType):
    id: str
    version: str
    jobControlOptions: Optional[List[JobControlOptions]] = None
    outputTransmission: Optional[List[TransmissionMode]] = None
    links: Optional[List[Link]] = None


class InputDescription(DescriptionType):
    minOccurs: Optional[int] = 1
    maxOccurs: Optional[Union[int, MaxOccurs]] = None
    schema_: Union[Schema, Reference] = Field(..., alias="schema")


class OutputDescription(DescriptionType):
    schema_: Union[Schema, Reference] = Field(..., alias="schema")


class InlineOrRefData(
    RootModel[Union[str, float, int, bool, List, Bbox, QualifiedInputValue, Link]]
):
    root: Union[str, float, int, bool, List, Bbox, QualifiedInputValue, Link]


class ProcessList(BaseModel):
    processes: List[ProcessSummary]
    links: List[Link]


class Process(ProcessSummary):
    inputs: Optional[Dict[str, InputDescription]] = None
    outputs: Optional[Dict[str, OutputDescription]] = None


class Execute(BaseModel):
    inputs: Optional[Dict[str, Union[InlineOrRefData, List[InlineOrRefData]]]] = None
    outputs: Optional[Dict[str, Output]] = None
    response: Optional[Response] = "raw"
    subscriber: Optional[Subscriber] = None


class Results(RootModel[Optional[Dict[str, InlineOrRefData]]]):
    root: Optional[Dict[str, InlineOrRefData]] = None


class InlineResponse200(
    RootModel[
        Union[
            str, float, int, Dict[str, Any], List[Dict[str, Any]], bool, bytes, Results
        ]
    ]
):
    root: Union[
        str, float, int, Dict[str, Any], List[Dict[str, Any]], bool, bytes, Results
    ]


Schema.model_rebuild()
