# generated by gen_server.py:
#   filename:  routes.py:
#   timestamp: 2025-06-23T09:10:09.259073


from s2gos.common.models import (
    ProcessRequest,
)

from .app import app
from .provider import ServiceProvider


# noinspection PyPep8Naming
@app.get("/")
async def get_landing_page():
    return await ServiceProvider.instance().get_landing_page()


# noinspection PyPep8Naming
@app.get("/conformance")
async def get_conformance_classes():
    return await ServiceProvider.instance().get_conformance_classes()


# noinspection PyPep8Naming
@app.get("/processes")
async def get_processes():
    return await ServiceProvider.instance().get_processes()


# noinspection PyPep8Naming
@app.get("/processes/{processID}")
async def get_process_description(processID: str):
    return await ServiceProvider.instance().get_process_description(
        process_id=processID
    )


# noinspection PyPep8Naming
@app.post("/processes/{processID}/execution")
async def execute(processID: str, request: ProcessRequest):
    return await ServiceProvider.instance().execute(
        process_id=processID, request=request
    )


# noinspection PyPep8Naming
@app.get("/jobs")
async def get_jobs():
    return await ServiceProvider.instance().get_jobs()


# noinspection PyPep8Naming
@app.get("/jobs/{jobId}")
async def get_status(jobId: str):
    return await ServiceProvider.instance().get_status(job_id=jobId)


# noinspection PyPep8Naming
@app.delete("/jobs/{jobId}")
async def dismiss(jobId: str):
    return await ServiceProvider.instance().dismiss(job_id=jobId)


# noinspection PyPep8Naming
@app.get("/jobs/{jobId}/results")
async def get_result(jobId: str):
    return await ServiceProvider.instance().get_result(job_id=jobId)
