# generated by gen_server.py:
#   filename:  service.py:
#   timestamp: 2025-06-23T09:10:09.387879

from abc import ABC, abstractmethod

from fastapi.responses import JSONResponse

from s2gos.common.models import (
    Capabilities,
    ConformanceDeclaration,
    JobInfo,
    JobList,
    ProcessDescription,
    ProcessList,
    ProcessRequest,
    ProcessResults,
)


class Service(ABC):
    @abstractmethod
    async def get_landing_page(self) -> Capabilities | JSONResponse:
        pass

    @abstractmethod
    async def get_conformance_classes(self) -> JSONResponse | ConformanceDeclaration:
        pass

    @abstractmethod
    async def get_processes(self) -> ProcessList | JSONResponse:
        pass

    @abstractmethod
    async def get_process_description(
        self, process_id: str
    ) -> ProcessDescription | JSONResponse:
        pass

    @abstractmethod
    async def execute(
        self, process_id: str, request: ProcessRequest
    ) -> JobInfo | JSONResponse:
        pass

    @abstractmethod
    async def get_jobs(self) -> JSONResponse | JobList:
        pass

    @abstractmethod
    async def get_status(self, job_id: str) -> JobInfo | JSONResponse:
        pass

    @abstractmethod
    async def dismiss(self, job_id: str) -> JobInfo | JSONResponse:
        pass

    @abstractmethod
    async def get_result(self, job_id: str) -> ProcessResults | JSONResponse:
        pass
