# generated by gen_server.py:
#   filename:  service.py:
#   timestamp: 2025-06-22T20:18:13.691438

from abc import ABC, abstractmethod

from fastapi.responses import JSONResponse

from s2gos.common.models import (
    ConfClasses,
    JobInfo,
    JobList,
    LandingPage,
    ProcessDescription,
    ProcessList,
    ProcessRequest,
    ProcessResults,
)


class Service(ABC):
    @abstractmethod
    async def get_landing_page(self) -> JSONResponse | LandingPage:
        pass

    @abstractmethod
    async def get_conformance_classes(self) -> JSONResponse | ConfClasses:
        pass

    @abstractmethod
    async def get_processes(self) -> JSONResponse | ProcessList:
        pass

    @abstractmethod
    async def get_process_description(
        self, process_id: str
    ) -> JSONResponse | ProcessDescription:
        pass

    @abstractmethod
    async def execute(
        self, process_id: str, request: ProcessRequest
    ) -> JSONResponse | JobInfo:
        pass

    @abstractmethod
    async def get_jobs(self) -> JSONResponse | JobList:
        pass

    @abstractmethod
    async def get_status(self, job_id: str) -> JSONResponse | JobInfo:
        pass

    @abstractmethod
    async def dismiss(self, job_id: str) -> JSONResponse | JobInfo:
        pass

    @abstractmethod
    async def get_result(self, job_id: str) -> JSONResponse | ProcessResults:
        pass
