# generated by gen_server.py:
#   filename:  transport.py:
#   timestamp: 2025-06-08T20:15:02.580419

from abc import ABC, abstractmethod

from fastapi.responses import JSONResponse

from s2gos.common.models import (
    ConfClasses,
    Execute,
    JobList,
    LandingPage,
    Process,
    ProcessList,
    Results,
    StatusInfo,
)


class Service(ABC):
    @abstractmethod
    async def get_landing_page(self) -> LandingPage | JSONResponse:
        pass

    @abstractmethod
    async def get_conformance_classes(self) -> ConfClasses | JSONResponse:
        pass

    @abstractmethod
    async def get_processes(self) -> ProcessList | JSONResponse:
        pass

    @abstractmethod
    async def get_process_description(self, process_id: str) -> Process | JSONResponse:
        pass

    @abstractmethod
    async def get_jobs(self) -> JobList | JSONResponse:
        pass

    @abstractmethod
    async def execute(
        self, process_id: str, request: Execute
    ) -> StatusInfo | JSONResponse:
        pass

    @abstractmethod
    async def get_status(self, job_id: str) -> StatusInfo | JSONResponse:
        pass

    @abstractmethod
    async def dismiss(self, job_id: str) -> StatusInfo | JSONResponse:
        pass

    @abstractmethod
    async def get_result(self, job_id: str) -> Results | JSONResponse:
        pass
